upstash/workflow-js

src/context/auto-executor.test.ts
src/context/auto-executor.ts
src/context/context.test.ts
src/integration.test.ts
src/receiver.test.ts
src/serve/authorization.test.ts
src/serve/serve.test.ts
src/test-utils.ts
src/workflow-parser.test.ts
src/workflow-parser.ts
src/workflow-requests.test.ts
src/workflow-requests.ts

We now stringify whatever is in step.out before sending steps to QStash. Consequently, we parse the out field of incoming steps.

Stringify/parse step.out

---

src/context/auto-executor.test.ts
src/context/context.test.ts
src/serve/authorization.test.ts
src/serve/serve.test.ts
src/workflow-requests.test.ts
src/workflow-requests.ts

feature header was supposed to only be sent in context.call instead of all requests. this is fixed
also, we don't forward the protocol header in the context.call request. this way, the request QStash makes doesn't have protocol header. so you can call another workflow endpoint.
merge after #5

Fix Protocol and Feature Headers in context.call

---

src/context/auto-executor.test.ts
src/context/context.ts
src/context/steps.test.ts
src/context/steps.ts
src/context/types.ts
src/serve/serve.test.ts
src/types.ts

Right now, the only way to pass durations is by number as below.
```javascript
await context.sleep("wait-until-welcome-email", 60 * 60 * 24);
```
With this PR, we're introducing a `Duration` type, where interface allows to pass durations as `1d`, `90m` etc. as below
```javascript
await context.sleep("wait-until-welcome-email", "90m");
```

String Duration Support for context.sleep and context.waitForEvent timeout

---

src/context/auto-executor.ts

Equivalent of https://github.com/upstash/qstash-js/pull/210 for workflow-js
This will allow running workflow with Node versions before Node v20.

Sort steps with .sort instead of .toSorted

---

examples/nextjs/app/-call-qstash/route.ts
examples/nextjs/app/auth/route.ts
src/client/index.test.ts
src/client/index.ts
src/context/steps.test.ts
src/serve/serve.test.ts
src/types.ts
src/utils.test.ts
src/utils.ts
src/workflow-parser.ts

Adds a method for triggering workflows which returns the workflow run id. It is now possible to:
- pass your own workflow run id
- receive the final workflow run id as result
```ts
const { workflowRunId } await client.trigger({
url: "https://workflow-endpoint.com",
body: "hello there!", // optional body
headers: { ... }, // optional headers
workflowRunId: "my-workflow", // optional workflow run id
retries: 3 // optional retries in the initial request
})
console.log(workflowRunId)
// prints wfr_my-workflow
```
the result workflow run id will always have `wfr_` prefix.
when passing a workflow run id, users should use a different workflow run id used everytime. Otherwise, there could be issues in the console view. In the image below, finished workflow runs show RUN_STARTED because another …

Add client.trigger

---

platforms/express.ts
src/context/auto-executor.ts
src/context/context.test.ts
src/context/context.ts
src/context/steps.test.ts
src/context/steps.ts
src/integration.test.ts
src/serve/serve.test.ts
src/types.ts
src/workflow-parser.ts
src/workflow-requests.ts

Adds `retries` parameter to `context.call` to make it possible to set the number of times the external call will retry.
```ts
await context.call("call", {
url: ...,
retries: 3
})
```
default value is 0 retry.
Also, added back the return type generic for context.call:
```ts
// body will be MyType
const { body } = await context.call<MyType>(...)
```

Add context.call retry option

---

src/client/index.test.ts
src/client/index.ts

update client.cancel to cancel all workflows or cancel a set of workflows or based on a workflow url
There are multiple ways you can cancel workflows:
- pass one or more workflow run ids to cancel them
- pass a workflow url to cancel all runs starting with this url
- don't pass any options. in this case, all workflow will be canceled
```ts
// cancel a single workflow
await client.cancel({ ids: "<WORKFLOW_RUN_ID>" })
// cancel a set of workflow runs
await client.cancel({ ids: [
"<WORKFLOW_RUN_ID_1>",
"<WORKFLOW_RUN_ID_2>",
]})
```
If you have an endpoint called `https://your-endpoint.com` and you
want to cancel all workflow runs on it, you can use `urlStartingWith`.
Note that this will cancel workflows in all endpoints under
`https://your-endpoint.com`.
```ts
await client.cancel({ …
```

Update cancel method

---

examples/ci/app/test-routes/failureFunction/route.ts
src/workflow-parser.ts

when initial payload was undefined, we would try to decode it, which would result in this error Failed while decoding base64 undefined

Handle undefined body correctly in failureFunction

---

src/context/auto-executor.ts
src/context/context.test.ts
src/context/context.ts
src/context/steps.test.ts
src/context/steps.ts
src/workflow-requests.ts

Adds timeout parameter to context.call:
```ts
context.call("my-step", {
url,
body,
headers: { "my-header": "my-value" },
method: "PATCH",
retries: retries,
timeout: 30,
});
```
Also add an error when step name is undefined or empty string.
`getHeaders` method is becoming a little to crowded, but we are planning to refactor that in the future.

Add timeout parameter to context.call

---

platforms/hono.ts

From [discord support](https://discord.com/channels/807028371451936838/1303907030117122100/1303907030117122100)
---
https://upstash.com/docs/workflow/quickstarts/hono#step-3-create-a-workflow-endpoint in this example which showcases using hono context in the workflow serve. It only has support for Bindings. I am not able to configure or type Variables in the serve function so the handler(c) is throwing a lint error saying it cannot accept the payload. 
the following is my Hono object creation code. 
```ts
interface Bindings extends WorkflowBindings {
db:MyDb
}
export const workflowsHandler = new Hono<{
Variables: RootVariables;
Bindings: Bindings;
}>();
```

Add typing support for hono variables in the handler

---

src/serve/options.ts
src/serve/serve.test.ts
src/workflow-requests.test.ts

Additionally, we print a warning log if the url has localhost.

Throw when workflow url doesn't start with http:// or https://

---

src/context/auto-executor.ts
src/types.ts
src/workflow-requests.test.ts

Similar to #16, we should rethrow the QStash error when submitting steps to QStash if the status is 400, which indicates that the workflow is canceled.
When we rethrow, it will be caught in https://github.com/upstash/workflow-js/blob/76f674a326c94f596dd33ac7e763b0fc64dd2684/src/workflow-requests.ts#L107 and handled.

Ignore wf canceled error in partial parallel execution

---

src/agents/adapters.ts
src/agents/index.ts
src/agents/task.test.ts
src/context/api/openai.ts
src/context/context.test.ts

Adds optional baseURL parameters to `context.api.openai.call` and `context.agents.openai`:
`context.api.openai.call`:
```ts
context.api.openai.call(stepName, {
token: openAIToken,
operation: "chat.completions.create",
baseURL: "https://api.deepseek.com",
timeout,
body: {
model: "gpt-4o",
messages: [
{
role: "system",
content: "Assistant says hello!",
},
{ role: "user", content: "User shouts there!" },
],
},
})
```
`context.agents.openai`:
```ts
context.agents.openai("gpt-3.5-turbo", { baseURL: "https://api.deepseek.com/v1" })
```

Accept baseURL in openai

---

platforms/express.ts
src/workflow-requests.ts

the problem was that in lazy fetch, QStash sends an empty request with content-type: application/json. express interprets this as {} ([see code](https://github.com/expressjs/body-parser/blob/a7293977ddd1a2e976b85f76db06d24b1575b784/lib/types/json.js#L78)). There is no option to configure this behavior.
In order to fix this problem, we will replace the body with empty string when the content type is application/json and content-length is 0.

DX-1611: Fiz lazy fetch in express-js

---

src/agents/adapters.test.ts
src/agents/adapters.ts
src/agents/types.ts
src/client/index.ts
src/index.ts

WorkflowTool will make it possible to define a tool which doesn't wrap invoke:
```ts
import { WorkflowTool } from "@upstash/workflow"
const agent = context.agents.agent({
tools: {
nonwrappedWorkflowTool: new WorkflowTool({
description: workflowToolDescription,
schema: parameters,
invoke: async ({ expression }) => {
await context.sleep(`step ${expression}`, 1000)
},
wrap: false
})
}
...
})
```

Add WorkflowTool

---

src/serve/serve-many.test.ts
src/serve/serve-many.ts

`workflowRunId` field in the invoke request body wasn't set correctly, causing the logs to be incorrect.

Fix workflowRunId field in invoke

---

platforms/hono.ts

Unlike the `serve` method in hono, `createWorkflow` method was missing the generics for Variables and Bindings.
This was noted by a user in discord ([link](https://discord.com/channels/807028371451936838/1343233001651306588)).
This PR fixes the issue by adding the generics available in `serve` to `createWorkflow`.

Fix add bindings and variables generics to hono `createWorkflow`

---

examples/ci/app/test-routes/call/constants.ts
examples/ci/app/test-routes/call/third-party/route.ts
examples/ci/app/test-routes/call/workflow/route.ts
src/context/auto-executor.ts
src/context/context.test.ts
src/types.ts
src/workflow-requests.ts

in context.call, if the user provided content-type, we were sending it like , but QStash ignores this if there is a  header.
since batchJSON added the content-type: application/json, we were unable to change the content-type. In the new version, we use batch instead of batchJSON and use the headers provided in the step as content-type if they are given.
fixes https://github.com/upstash/workflow-js/issues/70

DX-1680: Send correct content-type in context-call

---

src/error.ts
src/serve/index.ts
src/serve/options.ts
src/serve/serve.test.ts
src/types.ts

This PR adds a new `onError` callback option to the `serve` function, allowing users to provide custom error handling logic when errors occur during workflow execution.
Previously, when errors occurred during workflow execution, they were simply logged to the console with `console.error(error)`. This made it difficult for users to:
1. Implement custom error logging/monitoring
2. Handle specific error types differently
3. Collect error data for debugging purposes
The new `onError` callback gives users full control over error handling while still maintaining the default response behavior.
- Added `onError` option to the `WorkflowServeOptions` type
- Added clear JSDoc documentation explaining the difference between `onError` and `failureFunction`
- Updated error handling in `serveBase` to …

feat: add onError support to serve

---

src/agents/adapters.ts
src/agents/agent.test.ts
src/agents/index.ts
src/agents/types.ts
src/context/auto-executor.ts
src/context/steps.ts
src/qstash/submit-steps.ts

Adds a way to pass context.call settings when defining an agent:
```ts
const model = context.agents.openai("gpt-3.5-turbo", {
callSettings: {
flowControl: {
key: flowControlKey,
parallelism: 2,
},
retries: 5,
timeout: 10,
},
});
```

DX-1792: Allow passing context.call settings when defining agent

---

platforms/hono.ts

It looks like context.env is only defined in Cloudflare Workers. https://hono.dev/docs/api/context#env
When the serve method from hono is used in vercel, context.env is undefined which causes an error.
Fixed the issue by checking if context.env is defined and falling back to process.env if it isn't.
Fixes: https://github.com/upstash/workflow-js/issues/91

Use process.env if context.env isn't defined in hono

---

src/context/steps.test.ts
src/context/steps.ts

We were planning to throw initially. But that's a breaking change. Should be done in a major release or when we are certain that no-one is encountering this error.

Fix: Add warning for non-string step names

---

src/context/steps.ts
src/serve/serve.test.ts

We checked for exact match for "application/json" etc in the response headers of a context.call. If we determine that the response is text, we try to parse it.
Rerank endpoint of resend responded with application/json; charset=utf-8, which meant that we don't parse the body, resulting in this issue https://github.com/upstash/workflow-js/issues/93
Fixes https://github.com/upstash/workflow-js/issues/93

DX-1902: Check for includes instead of exact match in isText

---

src/context/steps.ts
src/serve/authorization.ts

The users shouldn't throw errors before the first step.
This will automatically make the auth attempt fail and workflow/failure function etc won't execute.
So we add a warning saying that this was unexpected.

DX-1996: print warning if error in custom auth
